# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 00:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginregister.User'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
