# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20170626_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='review',
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.SmallIntegerField(default=5),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
